### PR TITLE
hciuart: change WantedBy to dev-serial1.device

### PR DESCRIPTION
**Pull request by XECDesign**
Previously, the "After" parameter had no effect, as systemd is not aware
of what devices may come up. In some cases, hciattach was running before
/dev/serial1 was present. With this change, systemd will only try to
load this unit after it is aware of serial1.

### CODE REVIEW

**Comment by XECDesign** [comment]
@pelwell, this seems to work in my testing. Are there any potential problems with this I might have not thought about?

**Comment by pelwell** [comment]
It works for me as well. I didn't know you can use devices in that way.

**Comment by XECDesign** [comment]
Thanks. Looks like on pi-bluetooth upgrade, the `/etc/systemd/system/multi-user.target.wants/hciuart.service` symlink is kept in place until the service is disabled and re-enabled. Trying to figure out how to get it to do the right thing before I merge it.

**Comment by XECDesign** [comment]
Debhelper is meant to be able to cope with `WantedBy` changes, but I haven't made sense of how it's meant to work.

It seems to fall over [here](https://salsa.debian.org/debian/init-system-helpers/-/blob/master/script/deb-systemd-helper#L268).

`no_link_installed` parses the new `.service` file and if it doesn't find the `WantedBy` symlink, returns true. Then `create_links` is set to `0` and `make_systemd_links` doesn't do anything useful.

I've added a [workaround](https://github.com/RPi-Distro/pi-bluetooth/pull/33/commits/3a6f3afe0e62bed8c5930e445e7a77ff1843abfe), since I'm not sure whether that's a bug. In my testing it now works as intended, but I'll hold off from pushing it to the public apt repo for now.

**Pull request merged**
