### PR TITLE
Do not wait for hciuart before staring bluetoothd

### LINKED ISSUE #3: hciuart holding off start of bluetoothd
Newer (upstream) kernels have the ability to manage the uart connection and load firmware themselves, without a need for the hciattach daemon.

However when using such kernel with Raspbian it currently takes a minute or two before bluetooth works.
This is because your hciuart service is waiting a long time for `dev-serial1` to appear (which never will, as device is claimed by kernel), before eventually timing out.
Since you have `Before=bluetooth.service` that prevents startup of bluetoothd during that time.

It would be nice if hciuart didn't hold off starting up bluetoothd.
Isn't it capable of dealing with hci devices appearing later?

### PR DESCRIPTION
**Pull request by maxnet**
- Remove Before=bluetooth.service in hciuart service.
- Change "Wants=dev-serial1" to "Requires=dev-serial1" because
  with "Wants" it runs the script anyway after timeout, even
  though device does not exists.
- Invoke bthelper through udev rules.
  This is done indirectly through bthelper@hci0 service, because
  if run directly as udev script it results in a
  "Can't open HCI socket.: Address family not supported by protocol"
  error, due to RestrictAddressFamilies security setting in
  /lib/systemd/system/systemd-udevd.service not allowing AF_BLUETOOTH

Closes #3

### CODE REVIEW

**Comment by XECDesign** [comment]
Works for me, but there are some things to run by @spl237 and @pelwell, both of whom are away right now.

```
Aug 09 13:47:20 serge-poehat bluealsa[361]: /usr/bin/bluealsa: No HCI device available
Aug 09 13:47:20 serge-poehat systemd[1]: bluealsa.service: Main process exited, code=exited, status=1/FAILURE
Aug 09 13:47:20 serge-poehat systemd[1]: bluealsa.service: Unit entered failed state.
Aug 09 13:47:20 serge-poehat systemd[1]: bluealsa.service: Failed with result 'exit-code'.
...
Aug 09 13:47:27 serge-poehat bluetoothd[709]: Failed to set privacy: Rejected (0x0b)
...
Aug 09 13:50:10 serge-poehat systemd[1]: Started Raspberry Pi bluetooth helper.
Aug 09 13:50:16 serge-poehat systemd[1]: Started Raspberry Pi bluetooth helper.
Aug 09 13:50:16 serge-poehat bluetoothd[709]: Unable to get connect data for Headset Voice gateway: getpeername: Transport endpoint is not connected (107)
Aug 09 13:50:16 serge-poehat bluetoothd[709]: Endpoint registered: sender=:1.4 path=/A2DP/SBC/Source/2
Aug 09 13:50:21 serge-poehat bluealsa[710]: /usr/bin/bluealsa: Unsupported AT message: SET: command:+CLIP, value:1
Aug 09 13:50:21 serge-poehat bluealsa[710]: /usr/bin/bluealsa: Unsupported AT message: CMD: command:+CLCC, value:(null)
Aug 09 13:51:23 serge-poehat bluetoothd[709]: /org/bluez/hci0/dev_08_DF_1F_81_E4_41/fd0: fd(26) ready
Aug 09 13:55:24 serge-poehat systemd[1]: Started Raspberry Pi bluetooth helper.
Aug 09 13:55:30 serge-poehat systemd[1]: Started Raspberry Pi bluetooth helper.
Aug 09 13:55:56 serge-poehat systemd[1]: Started Raspberry Pi bluetooth helper.
Aug 09 13:56:37 serge-poehat systemd[1]: Started Raspberry Pi bluetooth helper.
```
Looks like mostly problems with bluealsa, but bthelper runs multiple times. there's `@hci0` and instances like `@hci0:11`, which I'm guessing is for each connected device.

EDIT: typo

**Comment by maxnet** [comment]
>Looks like mostly problems with bluealsa, but bthelper runs multiple times. there's @hci0 and instanced 
>like @hci0:11

Strange.
Would expect KERNEL=="hci[0-9]*" to only match hci0, hci1, etc.

**Comment by maxnet** [comment]
My bad, thought udev supported regular expressions. But * means shell style wildcard.

**Comment by maxnet** [comment]
>Aug 09 13:47:20 serge-poehat bluealsa[361]: /usr/bin/bluealsa: No HCI device available

Bluealsa is being run before there is a hci0 due to `WantedBy=multi-user.target` here: https://github.com/raspberrypi-ui/bluealsa/blob/master/debian/bluealsa.service#L12
You should be able to remove that, as it is already started by udev rule as well: https://github.com/raspberrypi-ui/bluealsa/blob/master/debian/bluealsa.udev

No need to have it started in two different ways.

**Comment by XECDesign** [comment]
Thanks, Floris. Should show up in the repo shortly.

**Pull request merged**
